### ISSUE TITLE
utf-8 characters break in IE, with no fallback

### ISSUE THREAD

**Issue by tmcw** [ded/sink-test#4]
Sorry about all the IE tickets, it sucks; as do the hours I'm spending today fighting with it. But, anyway, in IE, checks and crosses come out as equally-sized blank boxes, and there's no other indication on the page of individual tests passing and failing. Would be useful to have something else.

**Comment by ded** [comment]
usually if something fails, it turns red... and more than likely i wasn't too concerned about stuff not looking super pretty as long as i knew stuff passed.

in the meantime, have you added this to your page?

``` html
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
```

**Comment by tmcw** [comment]
@ded the concern was about sub-tests - the group turns red, but the subtests have no indication of pass/fail except for the checks and x'es.

**Comment by rvagg** [comment]
@tmcw - see latest version of sink-test with green/red boxes for subtests so it doesn't matter about the tick and cross.
But, if you want ticks and crosses in most browsers except IE6, I've just discovered that you can install more complete fonts that have all the necessary UTF8 characters in Windows XP if you go to _Control Panel->Regional and Language Options->Languages_ and tick the boxes at the bottom: _Install files for complex script and right-to-left languages (including Thai)_ and _Install files for East Asian languages_. It'll install files from the install CD and after a reboot you should see ✓ and ✗. Seems to work for IE7+ and others.

This issue can probably be closed since we have the _indication_ now.
